[package]
name = "provider-management"
description = "Privacy Providers Management Module"
version = "1.0.0"
edition = "2021"


[lib]
crate-type = ["rlib"]

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
